### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ChaoyiXie** [KAIST-VCLAB/sphere-stereo#1] opened 2021-10-26 09:41 UTC
when I run: 
python python/main.py --dataset_path resources --references_indices 2 3  --visualize True
then:
  File "python/main.py", line 93, in <module>
    args.sigma_i, args.sigma_s, args.device)
  File "/home/xcy/code/Real-Time_Sphere_Sweeping_Stereo_From_Multiview_Fisheye_Images/python/depth_estimation.py", line 72, in __init__
    self.cost_filter = ISB_Filter(candidate_count, matching_resolution, device)
  File "/home/xcy/code/Real-Time_Sphere_Sweeping_Stereo_From_Multiview_Fisheye_Images/python/isb_filter.py", line 51, in __init__
    cuda_source = cuda_source.replace("CANDIDATE_COUNT", str(candidate_count))
TypeError: a bytes-like object is required, not 'str'

**Comment by ameuleman** [comment] 2021-10-26 10:57
Thank you for reaching out.
I could not reproduce your issue. Would it be possible to print cuda_source as well as casting it as str?
cuda_source = str(cuda_source).replace("CANDIDATE_COUNT", str(candidate_count))

**Comment by ameuleman** [comment] 2021-11-11 08:42
As we did not get updates since my last message, I am closing the issue.
Please feel free to open a new one if you are still struggling with this problem or if you have others.

**Closed as completed by ameuleman** 2021-11-11 08:42 UTC
